### ISSUE TITLE
model.predict_for_customers()

### ISSUE THREAD

**Issue by rafarui** [EthanRosenthal/DataPiques_source#2]
Hello,First of all, great tutorial post. I am referring to the post 
>  Intro to Implicit Matrix Factorization: Classic ALS with Sketchfab Models

Two comments I have. 
1.  you said that you are using the implicit package, and it seems that in the class AlternatingLeastSquares there is no  method predict_for_customers(). Have you created your own version of the ALS class? You mentioned that before getting the item-to-item recommendations. 
> To get item-to-item recommendations, I made a small method ```predict_for_items``` in the ```ALS``` class. 

Is the predictor_for_user simply: ```predict_for_customers = model.user_factors.dot(model.item_factors.T)```

2. In the function ```learning_curve()```, why do you have this if statement
```python
for epoch in epochs:
    model.iterations = epoch - prev_epoch
    if not hasattr(model, 'user_vectors'):
        model.fit(train)
    else:
        model.fit_partial(train)
```

Tks.

**Comment by EthanRosenthal** [comment]
Hi @rafarui 

For comment 1, you're correct about the form of `predict_for_customers`. See the code [here](https://github.com/EthanRosenthal/implicit/blob/master/implicit/implicit.py#L93).

For comment 2, I have the `if` statement to be able to pick up training where I left off in the previous iteration. If you call `fit`, then it initializes the user and item vectors. If the model already has user and item vectors, then these will be _overwritten_ on calling `fit` again. `fit_partial` continues training. The very first time the model is called, I want to initialize the user and item vectors. The way to tell if the model has been initialized is by whether or not it has user and item vectors as attributes.

**Comment by rafarui** [comment]
Thanks @EthanRosenthal 
The link for the code seems to be wrong. 

I understood now the `fit_partial`. So you are using the LightFM package instead of the implicit in [this post](http://blog.ethanrosenthal.com/2016/10/19/implicit-mf-part-1/).

PS: I am studying recommender models nad I learnt today about the the project you are involved [spotlight](https://github.com/maciejkula/spotlight) project. That seems really nice.

**Comment by EthanRosenthal** [comment]
Whoops! Link fixed. No, I don't use LightFM in that post. I use a fork that I made of the implicit package (which I've now correctly linked to in my previous comment).

And yeah, spotlight is great! [Maciej Kula](https://github.com/maciejkula) built it - he also made LightFM.

**Comment by rafarui** [comment]
tks again, the code will help me a lot.
